### ISSUE TITLE
v0.11 cli don't compile 

### ISSUE THREAD

**Issue by pepejr-cyber** [RGB-WG/rgb#106]
the doc in readme.md is wrong .  

cargo install rgb-wallet won't compile as it looks for an exe 

cargo install --path . --all-features in /cli  ( the old command ? )  allmost work . but not  :) 

<img width="563" alt="Screenshot 2024-01-22 at 15 19 58" src="https://github.com/RGB-WG/rgb/assets/4004560/db35be00-5282-4be0-800d-cf1d30f1aa12">

**Comment by shuimuliang** [comment]
plz compile it with branch v0.11, it works.

**Comment by pepejr-cyber** [comment]
i am on branch V0.11 .  

but is it ok to go to ./cli and try compile with cargo install --path . --all-features ? 

because cargo install rgb-wallet   doesn't even start ! 

sorry for that . I'm on a macbook air absolutely new and fresh installed everything ( for rgb ) .
<img width="564" alt="Screenshot 2024-01-24 at 19 30 52" src="https://github.com/RGB-WG/rgb/assets/4004560/ae7942d4-8005-4c53-920f-60265f7a9a62">

**Comment by cymqqqq** [comment]
the same operation but different errors here, first I run cargo update, then cargo install --path . --all-features/cargo install --path . --force in cli directory, but it not works :(
<img width="693" alt="image" src="https://github.com/RGB-WG/rgb/assets/8555534/e04e2536-7955-4503-a724-a1b44d5388ff">
I tried on branch master, v0.11, and v0.11-beta3, none of them works, and the same error as the above figure.

**Comment by dr-orlovsky** [comment]
https://github.com/RGB-WG/rgb/issues/133#issuecomment-1949337656
