### ISSUE TITLE
Question about the rgb-runtime

### ISSUE THREAD

**Issue by cymqqqq** [RGB-WG/rgb#129]
Here,
<img width="604" alt="image" src="https://github.com/RGB-WG/rgb/assets/8555534/0cef751c-231c-400a-a44d-df3d85cbd627">
For this code, what's the idea of importing bp-wallet runtime? Do we need to use bp-wallet instead of bdk wallet? (Include construct psbt, sign psbt, and so on)

**Comment by cymqqqq** [comment]
I wrote this code
<img width="946" alt="image" src="https://github.com/RGB-WG/rgb/assets/8555534/1102ab59-614f-42af-8b66-90ff0892da59">
to load the runtime. First, I create data0/testnet directory, then I execute this code, the error print out(I want to use rgb runime to import rgb contract in command line):
<img width="383" alt="image" src="https://github.com/RGB-WG/rgb/assets/8555534/07cc2123-4436-4cd4-a7f4-c45038d58b93">
In the bp-wallet, the path should be
data0/testnet/descriptor.toml
data0/testnet/data.toml
I don't know whether I missed some steps.

**Comment by dr-orlovsky** [comment]
RGB wallet is the RGB+wallet solution we provide by default. You are not required to use it, RGB std is enough - but you would need to integrate it with the wallet of your choice (like BDK) by yourself.

From our experience you can't get BDK to work with tapret commitments, thus we had to develop BP wallet and use it here.

Regarding your error, can you replicate what we do in `rgb`:
https://github.com/RGB-WG/rgb/blob/a773b7dd45ef6341b7c337e864871e8dfb4be542/cli/src/args.rs#L72-L76

This creates all necessary directories, files etc. Do not create them manually.

**Comment by cymqqqq** [comment]
So, in your words, for the tapret commitment, the next step we need to implement is how to sign psbt, and how to extract a transaction from psbt with bp-wallet, right? (Just like BDK does)

**Comment by dr-orlovsky** [comment]
You can sign PSBT with any PSBT signer made in any language (not even Rust) - even like Sparrow wallet. Tapret doesn't affect the signing part.
