### ISSUE TITLE
One seal can bind any count RGB20 assets

### ISSUE THREAD

**Issue by Matrix-Zhang** [RGB-WG/rgb#138]
I had tried to issue some RGB20 assets with same seal (same utxo). the RGB runtime can import and store with no errors.

**Comment by dr-orlovsky** [comment]
Yes, this is how it should be. Why did you open an issue?

**Comment by dr-orlovsky** [comment]
Please feel free to re-open if you have arguments and design how it can be done any other way

**Comment by Matrix-Zhang** [comment]
> Yes, this is how it should be. Why did you open an issue?

so, my question is if I have Asset A and Asset B both bind same one utxo belong me,
and then I transfer some Asset A to someone if bob, the utxo is spend, and a new utxo pointer the Asset A
but Asset B is still pointer the old utxo. 

How to identify the Asset B's state? if the wallet client should tract the transit chain?

**Comment by Matrix-Zhang** [comment]
by the way, i can't reopen the issue...

**Comment by dr-orlovsky** [comment]
The wallet must create so-called "blank state transition" for each contract each is assigned to the UTXO other than the contract of the transaction. These state will be re-assigned to the change UTXO in the witness transaction - or one of other already existing UTXOs in the wallet.

There is no technical way to prevent multiple contracts from assigning the same UTXO state under multiple seals.
