### ISSUE TITLE
replace panic for usupported liquid with error

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#151]
I think we should replace the panics saying "Liquid is not yet supported" (e.g. https://github.com/RGB-WG/rgb/blob/master/src/resolvers/electrum.rs#L168 and https://github.com/RGB-WG/rgb/blob/master/src/resolvers/esplora_blocking.rs#L110) with a dedicated error, because otherwise the validation of a consignment containing a liquid anchor can panic. I know it should be impossible creating such consignment with current crates, but a malicious user could edit the consignment using YAML import/export feature and upload it to the proxy (or another consignment transport medium) making a wallet panic.

@dr-orlovsky let me know if you want me to open a PR or if you prefer to do it

**Comment by dr-orlovsky** [comment]
You are right! If you have time to work on that it would be great. Otherwise I'll do it

**Comment by zoedberg** [comment]
Sure, I'll open a PR tomorrow
