### ISSUE TITLE
Change sent to an unknown address

### ISSUE THREAD

**Issue by Starlined** [RGB-WG/rgb#16]
I've run into quite a strange problem testing transfers using this RGB command line interface. I was following this video where Dr. Orlovsky performs a demo transaction ([link](https://www.youtube.com/watch?v=P5UQJAaan0I)). 

Upon following the video step for step I encountered an error right at the end when the transfer was broadcast to the blockchain. The RGB20 assets did indeed transfer and go to the correct address however the change did not, instead the change is sent to a random taproot address that the tpub does not have access to. This can be confirmed by running "rgb utxos" on corresponding wallet after the transfer is broadcast. It will be unable to see the change and the private key will have lost control of some amount of the assets.

At first I thought this was because of a mistake on our part however we noticed in the video Dr. Orlovsky had the exact same issue!

To provide a little bit more information and clarity.

In the video Dr. Orlovsky uses this TPUB: tpubDCNiWHaiSkgnQjuhsg9kjwaUzaxQjUcmhagvYzqQ3TYJTgFGJstVaqnu4yhtFktBhCVFmBNLQ5sN53qKzZbMksm3XEyGJsEhQPfVZdWmTE2

Which he creates an RGB wallet for with the descriptor tapret(tpubDCNiWHaiSkgnQjuhsg9kjwaUzaxQjUcmhagvYzqQ3TYJTgFGJstVaqnu4yhtFktBhCVFmBNLQ5sN53qKzZbMksm3XEyGJsEhQPfVZdWmTE2, ...)

He then issues 1000000000000000 of an RGB20 asset called TST to a UTXO associated with this wallet.

He then performs a transfer action where he transfers 100 TST to a new UTXO. He signs the transfer PSBT and then broadcasts it.

This is the transaction he broadcast in the video: https://www.blockstream.info/testnet/tx/85f9b8ce3b495a206de334928c89ce8fc93f02304b634641ac76e4008948e2a3

The transaction has 1 input (The UTXO which sealed the TST) and 1 output, which is the change from the transaction. The change also is the UTXO where the remaining TST is bound. The address the change is sent to is: tb1pmv024fd3f62peg5rg5ex8m3zl4n9qkze5xsrw58fknh5987hkmusflwcpu

The tpub from earlier is unable to detect the change utxo (85f9b8ce3b495a206de334928c89ce8fc93f02304b634641ac76e4008948e2a3:0) when calling "rgb utxos" OR when calling "btc-cold check <WALLETFILE>" furthermore the change utxo is unspent (meaning the problem is not that it has been spent). 

The result in the video and when we performed tests is that when you do a RGB transfer call the correct amount of assets get transferred to the person you want to send them to but the change gets sent to a random address meaning the original owner loses their RGB20 assets (or loses the ability to spend them). From what I can tell this looks like when the RGB CLI is manipulating the PSBT (through the transfer call) it is deriving the change address incorrectly from the tpub.

You can test this yourself by adding the TPUB Dr. Orlovsky used to the wallets on the RGB CLI.

`rgb create VideoWallet tpubDCNiWHaiSkgnQjuhsg9kjwaUzaxQjUcmhagvYzqQ3TYJTgFGJstVaqnu4yhtFktBhCVFmBNLQ5sN53qKzZbMksm3XEyGJsEhQPfVZdWmTE2`

and then by checking the utxos

`rgb utxos -w VideoWallet`

You will notice that there are no UTXOs from the transaction from the video and the wallet no longer owns the vast majority of TST tokens. The utxo is also unspent which we can see by checking the address associated with it which only has 1 transaction which is the transaction sending change to it. 

I'm assuming the error is caused by the client deriving the wrong change address when modifying the output of the PSBT file.

We can consistently reproduce this error and are happy to jump on a call to help identify and fix it. Any and all help would be appreciated.

**Comment by dr-orlovsky** [comment]
From what I understand from your explanation, this is not a bug but just confusion coming from the fact that single-use-seals tweak an output of the transaction spending the assets, which modifies the address. Still, the address is recognizable by an RGB-enabled wallet (which is aware of tweaks, which form a part of an extended descriptor). Since there were _no_ RGB-enabled wallets released (me and a few other teams are working on them these days expecting them to be present in the next (several) weeks), you do not see this output with a tweak.

Please also see an explanation from a duplicate issue here: https://github.com/RGB-WG/rgb-wallet/issues/53

**Comment by dr-orlovsky** [comment]
If you'd like to play with the assets before any wallet released you may use OP_RETURN-based commitments which will not tweak/modify an output. This can be done with `rgb transfer --method opret1st`.
