### ISSUE TITLE
InvalidCloseMethod error on 1st transfer

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#168]
After issuing an asset the first transfer fails throwing the following error:
```
thread 'main' panicked at psbt/src/lib.rs:89:18:
transitions are unique since they are in BTreeMap indexed by opid: InvalidCloseMethod(OpId(Array<32>(07feff20b7306b73dfbd2d55d5784ba99aeaf91f541f099fbc7cc1382823df84)))
```

The error comes from the `push_rgb_transition` method, where the check
```rust
if Some(method) != prev_method {
    return Err(RgbPsbtError::InvalidCloseMethod(opid));
}
```
throws the error because `prev_method` is `None`. The reason seems to be that the only push of the `rgb_closing_methods` proprietary key (used to retrieve the previous close method) is done in `push_rgb_transition` a little after this check, therefore I think `prev_method` will always be `None`.

**Comment by dr-orlovsky** [comment]
Is this in `v0.11` branch or `script-refactoring`?

**Comment by zoedberg** [comment]
> Is this in `v0.11` branch or `script-refactoring`?

On both branches

**Comment by dr-orlovsky** [comment]
Please check `v0.11` tip which not got fix in https://github.com/RGB-WG/rgb/commit/0e7858f0434089cf6d41563fa2a4de19d5bc4cf9

**Comment by zoedberg** [comment]
It has been fixed, thanks
