### ISSUE TITLE
kit import fails (script-refactor branch)

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#169]
When using the `script-refactor` branch, the `import` CLI command fails. Here the logs:
```
rgb -n regtest --electrum localhost:50001 -d data0 import -w wallet_1 ./rgb-schemata/schemata/NonInflatableAssets.rgb
RGB: command-line wallet for RGB smart contracts
     by LNP/BP Standards Association

Loading stock ... success
Error: unsupported value `136` for enum `Bool` encountered during decode operation
```

The error seems to be triggered by the call to `let content = UniversalFile::load_file(file)?;` and is raised by strict-encoding.

**Comment by dr-orlovsky** [comment]
Huh, I spent hours trying to detect why this happens - and just accidentally notice that the bug goes away after `cargo update -p rgb-std` (on `script-refactor` branch).

Huh

**Comment by zoedberg** [comment]
Sorry to hear that. Anyway I've retried and I confirm this is not an issue anymore. Closing this
