### ISSUE TITLE
global type doesn't match type definition: ExtraField(FieldName("naming"))

### ISSUE THREAD

**Issue by 0x000000000000000** [RGB-WG/rgb#177]
I used version v0.11.5 to compile rgb20, but this error occurred. How to solve it?
![屏幕截图 2024-04-25 173528](https://github.com/RGB-WG/rgb/assets/92365829/1483fccc-645e-4b91-bb6c-efe1ca537fc8)
![屏幕截图2 2024-04-25 174018](https://github.com/RGB-WG/rgb/assets/92365829/cacf4d04-6b3a-4451-b0e3-d40f368c2ac6)

**Comment by 0x000000000000000** [comment]
`interface: RGB20

globals:
  spec:
    ticker: DBG
    name: Debug asset
    details: "Pay attention: the asset has no value"
    precision: 0
  terms: 
    text: rgb20 asset
    media: ~
  issuedSupply: 1000

assignments:
  assetOwner:
    seal: opret1st:57b640f61013abcd7a1000ed59ca3bb86cebdfc00ab9b0da756b314b3d99f835:0
    amount: 1000
`
I need to modify the rgb20 yaml file so that it can be compiled and passed

**Comment by dr-orlovsky** [comment]
Fixed in `develop` branch
