### ISSUE TITLE
error compile 

### ISSUE THREAD

**Issue by W6Design** [RGB-WG/rgb#18]
Compiling rgb-contracts v0.10.0-beta.2 (C:\Users\serge\Documents\GitHub\rgb)
error[E0061]: this method takes 2 arguments but 1 argument was supplied
--> src\bin\rgb\command.rs:361:55
|
361 | if let Ok(allocations) = contract.fungible(owned.name.clone()) {
| ^^^^^^^^-------------------- an argument of type std::option::Option<&_> is missing

**Comment by dr-orlovsky** [comment]
Please try cloning the master and compiling from it
