### ISSUE TITLE
contract export fails

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#186]
Using the `develop` branch, contract export fails:
```
Error: contract rgb:JKzLcNnC-8LfkROJ-nj$RouW-YxumPiE-AE3UWzW-iRYx55s is unknown. Probably you haven't imported the contract yet.
It may happen due to RGB standard library bug, or indicate internal stash inconsistency and compromised stash data storage.
```

This is done from the same wallet that successfully issued it and the contract state is correctly reported:
```
Loading descriptor from wallet wallet_1 ... success
Global:
  spec := (ticker=("USDT"), name=("USD Tether"), details=~, precision=0)
  terms := (text=("demo NIA asset"), media=~)
  issuedSupply := (2000)

Owned:
  assetOwner:
    amount=2000, utxo=bc:opret1st:2fd6f7315143355495b92bf69bd895caa16d4a8fe8cb604b27881857f604d48b:0, witness=~ # owned by the wallet
```

**Comment by dr-orlovsky** [comment]
After multiple attempts can't reproduce...

**Comment by dr-orlovsky** [comment]
Does this issue still exists?

**Comment by nicbus** [comment]
> Does this issue still exists?

Yes, it still happens with `rgb` commit `4a498cc` and `rgb-schemata` commit `10e0ba8`, the outcome is the same.

I have updated `rgb-sandbox` and I can reliably reproduce it using this [branch](https://github.com/nicbus/rgb-sandbox/tree/contract_export_fail), running the following command:
```bash
./demo.sh -s 186 -v
```

The `-s 186` option means "run scenario 186", which has been created for this specific issue; you can find it at the end of the `demo.sh` file, it simply issues an asset and tries to export it.

The final cleanup is commented out, so at the end of the run you can access the wallet data to inspect the situation.

**Comment by dr-orlovsky** [comment]
@nicbus can you please update the sandbox to the released beta 6?

I have tried exporting contracts multiple times and it always works. It could be the reason in some invalid bash scripting or in the sandbox itself...

**Comment by nicbus** [comment]
I have updated the sandbox to beta 6 and, while there is at least one pending issue (#209), export now works.

I have heavily refactored the sandbox in the process, though, and I have fixed an issue about contract export, so I think that was the real cause.
