### ISSUE TITLE
electrum resolver: broken login

### ISSUE THREAD

**Issue by eauxxs** [RGB-WG/rgb#193]
when I run
` rgb create --tapret-key-only "****" --electrum "blockstream.info:110" -n bitcoin my-wallet`

```
Syncing keychain 0 ........... keychain 1 .......... keychain 9 .......... keychain 10 ..........thread 'main' panicked at 

~/.cargo/git/checkouts/bp-wallet-997f3c057e1b59f2/5d07f27/src/indexers/electrum.rs:278:52:
broken logic
```

Since some electrum server implementations do not support verbose, setting the second parameter of blockchain.transaction.get to true ([rgb](https://github.com/RGB-WG/rgb/blob/790ba4b18bb8097b0f51953097f51d2965528ec5/src/resolvers/electrum_blocking.rs#L46) and [bp-wallet](https://github.com/BP-WG/bp-wallet/blob/0009dc615ff4c44420408663ed09de9ea5a2c2b7/src/indexers/electrum.rs#L151)) will return an error. and results in broken login.

**Comment by eauxxs** [comment]
https://github.com/Blockstream/electrs/pull/36

**Comment by zoedberg** [comment]
@eauxxs Unfortunately the electrum server forked by Blockstream doesn't provide the functionality that RGB requires to check the TX confirmations.
Therefore I've added a check (https://github.com/RGB-WG/rgb/pull/194) to be sure we warn the user that the provided service is missing that functionality, which is definitely better that panicking.

If you want to use an electrum server for mainnet you can use `ssl://electrum.iriswallet.com:50003`

**Comment by eauxxs** [comment]
thanks your reply！@zoedberg
