### ISSUE TITLE
wrong balance after witness transfer

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#212]
Trying the usual transfer series via `rgb-sandbox`, using `rgb-wallet` from master (beta 6 + PR #211 for human-readable values), I run into an issue. After a witness transfer, the balance for the receiving wallet is incorrect.

Here are the steps to reproduce the problem, using 2 opret wallets:
- issue a NIA contract on wallet 0
- send some assets from wallet 0 to wallet 1 using a witness invoice

The transfer completes successfully, accept included. Here are the wallets' outpoints and contract states after the transfer:
- wallet 0
    ```
    Height     Amount, ṩ    Outpoint
    bcrt1qrjeyktuuchvks9x7vwf58tq5mjkduq5ghqzmma    &9/1
    105         99997600    5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b:1

     Owned:
      assetOwner:
        value=2000, utxo=bc:opret1st:9cc679405e0aa2ad4e79559aa3123831241f429875544af7d84880134a421525:1, witness=~ -- owner unknown
        value=100, utxo=bc:opret1st:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b:0, witness=bc:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b -- owner unknown
        value=1900, utxo=bc:opret1st:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b:1, witness=bc:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b
    ```
- wallet 1
    ```
    Height     Amount, ṩ    Outpoint
    Loading descriptor from wallet wallet_1 ... success

    Owned:
      assetOwner:
        value=2000, utxo=bc:opret1st:9cc679405e0aa2ad4e79559aa3123831241f429875544af7d84880134a421525:1, witness=~ -- owner unknown
        value=100, utxo=bc:opret1st:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b:0, witness=bc:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b -- owner unknown
        value=1900, utxo=bc:opret1st:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b:1, witness=bc:5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b -- owner unknown
    ```

It looks like wallet 1 doesn't see the UTXO from the transfer's tx (txid: `5f8491a78476b278bb981b2545b890e73847436558a40b69fe9957c2a2f5886b`) and thus sees no owned allocations, leading to a balance of 0, instead of the expected 100.
Printing the address used by the invoice I get `bcrt1qc7huwmgyuq6snsku0papx7grafde9fldhg73rz`, which does not appear in the generated PSBT.

Here are the wallets' data dirs:
[wallet_data.tar.gz](https://github.com/user-attachments/files/15888774/wallet_data.tar.gz)

**Comment by dr-orlovsky** [comment]
So basically it doesn't recognize tweak applied to the first tapret output, which is owned by wallet 1... Working on it

**Comment by nicbus** [comment]
After patching `rgb-std` to `master` for https://github.com/RGB-WG/rgb-std/issues/220 I have re-tested for this issue as well and it gone, too.

I don't think it had to do with tweaks, as both wallets are opret in this case and I use no special construction (just the regular CLI invoice/transfer commands). Still, I fail to see how switching to rgb-std master branch should have fixed this problem.

I'll leave this open for now so we can further discuss if needed, but the original problem is solved.

**Comment by dr-orlovsky** [comment]
Sorry, I have somehow read `opret` as `tapret`. Indeed, this is very strange...

**Comment by dr-orlovsky** [comment]
Seems we can close this now
