### ISSUE TITLE
provide offline methods

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#22]
The current implementation of `Runtime` requires a valid `electrum_url` in order to be loaded. This means that all RGB methods require to be online, even methods that do not have this requirement because they actually use only data saved on disk (e.g. `iface_by_name` and `contract_iface` to get asset metadata). I propose to make all methods that do not require a blockchain resolver available even when offline.

I think there are many ways to implement this. One solution could be: making the `electrum_url` parameter of `Runtime::load` an optional one, then of course make also the `resolver` `Runtime`'s' field optional and check for it's presence only on methods that actually need it, returning an error if the `Runtime` has been instantiated without an electrum URL.

@dr-orlovsky what do you think?

**Comment by dr-orlovsky** [comment]
Good point, will work on that!
