### ISSUE TITLE
PSBT finalization command missed

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb#230]

**Comment by nicbus** [comment]
I tried this in rgb-sandbox, using bp-wallet `52674cc` and rgb-wallet `18803d7` but I still the same error from https://github.com/BP-WG/bp-wallet/issues/58.

**Comment by nicbus** [comment]
Not really, but I guess I had some unwanted local changes, it shouldn't be anything hinting at possible problems with the fix.
