### ISSUE TITLE
rgb import rgb20-simplest.rgb  Command Errors

### ISSUE THREAD

**Issue by TanWanBenWan** [RGB-WG/rgb#251]
After successfully generating the contract file using cargo run, I encountered an error while executing the command rgb import examples/rgb20-simplest.rgb. The error messages stated 'stock file is damaged, failing' and 'Error: entity not found'. I'm quite frustrated and need guidance on what to do next

**Comment by zoedberg** [comment]
The file `examples/rgb20-simplest.rgb` doesn't exist. Moreover on beta 8 there is an issue on how a missing stock error is handled, https://github.com/RGB-WG/rgb/pull/248 fixes that.

**Comment by dr-orlovsky** [comment]
You should also remove contents of the old ~/.lnp-bp first

**Comment by romancerny** [comment]
deleted .lnp-bp folder content & using .rgb files from https://github.com/RGB-WG/rgb-schemata/tree/v0.11/schemata
 but still get:

❯ rgb import rgb-schemata/schemata/NonInflatableAssets.rgb
stock file is damaged, failing
Error: entity not found

please advise, thanks

**Comment by dr-orlovsky** [comment]
@romancerny I believe you are experiencing https://github.com/RGB-WG/rgb/pull/254

Can you please try using the code from that PR?

**Comment by romancerny** [comment]
@dr-orlovsky  that worked with following output. Thanks very much :-)

Importing kit rgb:kit:$Rniyeda-KT4Rnce-aN9gKgA-xkhhVMC-y4SEO8L-KQd9DYI:
- interface RGB20Fixed $iUnO9aO-1xhqUd6-1Jm5S5!-wM3ngby-5GVEylQ-ZTAMYDk#tornado-pioneer-bucket
- schema NonInflatableAsset RDYhMTR!9gv8Y2GLv9UNBEK1hcrCmdLDFk9Qd5fnO8k#brave-dinner-banana
- implementation of RGB20Fixed for NonInflatableAsset
- script library alu:q$CZ0ovt-UN9eBlc-VMn86mz-Kfd3ywu-f7$9jTB-k6A8tiY#japan-nylon-center
- strict types: 89 definitions
Kit is imported

**Comment by romancerny** [comment]
is this gonna be in rgb-wallet 0.11.0-beta.9 ?

**Comment by dr-orlovsky** [comment]
Yes

**Comment by romancerny** [comment]
If anyone finds this thread helpful: running following gives '!9: event not found' error which can be solved the same way as above :-)

rgb issue rgb:sch:RDYhMTR!9gv8Y2GLv9UNBEK1hcrCmdLDFk9Qd5fnO8k#brave-dinner-banana tprv8ZgxMBicQKsPeuLFQ6Ej8pKSxv7K1A4VwbAGBSTFwTyxkioeGKwV3nthVSnwJ41bWafzFoKPGQyNLnYcrEpsbWMUNKdwTtDRaWgGf1n38v5 /home/roman/.lnp-bp/rgb-examples/examples/rgb20-demo.yaml

Also, running it on the PR, there is 1 new argument <ISSUER>

sorry to ask here, what is 'Issuer identity string'? is it public key or private key? what format is it in?

Usage: rgb issue [OPTIONS] <SCHEMA> <ISSUER> <CONTRACT>

Arguments:
  <SCHEMA>    Schema name to use for the contract
  <ISSUER>    Issuer identity string
  <CONTRACT>  File containing contract genesis description in YAML format

Thanks

**Comment by dr-orlovsky** [comment]
In bash, `!` is a special symbol (like `$`) substituting for previous command. 

Pleas always keep any ids in single quote marks in the command-line (and not double-quotes)

**Comment by romancerny** [comment]
thank you for your help & patience :-)
