### ISSUE TITLE
rgb issue Error

### ISSUE THREAD

**Issue by machine-creek** [RGB-WG/rgb#40]
rgb import rgb20-demo.rgb This can be successful.

rgb issue 4h3xkAmiRdQs2HwQmnFVqoj5DG3NhGkJRpNZXjNrJT2N RGB20 examples/rgb20-demo.yaml
I still failed to use this command.

rgb issue 4h3xkAmiRdQs2HwQmnFVqoj5DG3NhGkJRpNZXjNrJT2N RGB20 examples/rgb20-demo.yaml
Error: schema urn:lnp-bp:sc:4h3xkA-miRdQs2H-wQmnFVqo-j5DG3NhG-kJRpNZXj-NrJT2N#vision-scuba-sample is unknown.
It may happen due to RGB standard library bug, or indicate internal stash inconsistency and compromised stash data storage.

I need to issue a new contract and recompile it instead of importing the already compiled contract.

**Comment by dr-orlovsky** [comment]
Duplicate: you need to import the schema first. Please see https://github.com/RGB-WG/rgb/issues/33

**Comment by dr-orlovsky** [comment]
Did you try against the latest master tip?

**Comment by dr-orlovsky** [comment]
Fixed in the latest master tip
