### ISSUE TITLE
de-accept a consignment

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#42]
If my understanding is correct, with current implementation we should accept a consignment only when we are confident the transfer is final and irreversible (enough blocks have been mined). For now this approach is ok but this could slow down RGB transfers. We think it would be nice to be able to accept consignments on 0/low-conf transactions and be able to de-accept a consignment in case of a re-org or an RBF. 
This is not urgent but a nice to have, IMO it can be done after 0.11 testing.

**Comment by zoedberg** [comment]
I'm not referring to a consignment that contains invalid data. I'm saying that a receiving wallet could allow receiving with 0-conf and the sender could then decide to RBF the transaction to speed up its mining process. In that case the sender would give an updated consignment to the receiver, that should accept it. But to accept this updated consignment the receiver should de-accept the previous consignment otherwise the wallet could consider the second consignment invalid, or even worse (depending on how this part has been implemented) it could think that he received the assets twice.

**Comment by dr-orlovsky** [comment]
> But to accept this updated consignment the receiver should de-accept the previous consignment otherwise

No

> otherwise the wallet could consider the second consignment invalid

No, there is no way how this can happen

> it could think that he received the assets twice.

again, this situation is not possible.


RGB stash reports state belonging to UTXOs. If UTXO doesn't exist (replaced by RBF) the state "disappears": it still exists in the stash but wallet is not reported on it.

If we "de-accept" the consignment for RBF, than in case of deep re-orgs where pre-RBF tx may replace the RBF one, we will use the state. Thus, stash never deletes anything
