### ISSUE TITLE
Unable to import any of the examples.

### ISSUE THREAD

**Issue by AurevoirXavier** [RGB-WG/rgb#43]
I have pulled the repository and all the code is up to date.

I received an error message when running `rgb -w xavier import examples/rgb20-demo.toml`.
```
Error: Invalid file data.
```

I received an error message while running `rgb -w xavier import examples/rgb20-demo.rgb`.
```
Error: Encountered unsupported value `1` for enum `ContainerVer` during decode operation.
```

**Comment by dr-orlovsky** [comment]
1. You can't import `toml` or other non-binary files - only ones with `.rgb` extensions (which is a binary bindle format)
2. Regarding the second case, it seems that you need to re-generate `examples/rgb20-demo.rgb` by running `cargo run --example rgb20` and try to import it then

**Comment by AurevoirXavier** [comment]
> 1. You can't import `toml` or other non-binary files - only ones with `.rgb` extensions (which is a binary bindle format)
> 2. Regarding the second case, it seems that you need to re-generate `examples/rgb20-demo.rgb` by running `cargo run --example rgb20` and try to import it then

Thanks for your reply.

But I got:
```
cargo run --example rgb20
error: no example target named `rgb20`.
```

**Comment by AurevoirXavier** [comment]
Ah, It looks there are still some breaking changes in recent versions?

```
rgb issue examples/rgb20-demo.yaml
error: invalid value 'examples/rgb20-demo.yaml' for '<SCHEMA>': non-parsable Baid58 string 'examples/rgb20-demo.yaml'
```

**Comment by AurevoirXavier** [comment]
> Yes, there are more. Try using the released version, master is not finalized yet and not compatible with `v0.10`

Thank you for your hard work. I've noticed that you maintain several repositories.

As a senior Rust developer, I'm enthusiastic about learning more and contributing to these libraries. However, I've been struggling to find a starting point, which is one of the reasons why I want to stay up-to-date with the latest code.

**Comment by dr-orlovsky** [comment]
We'd be glad to have you contributing to the project. If you'd like we can start with a call and discuss possible options.

**Comment by dr-orlovsky** [comment]
Fixed in the new release

**Comment by AurevoirXavier** [comment]
> We'd be glad to have you contributing to the project. If you'd like we can start with a call and discuss possible options.

Thank you.
Honestly, I don't want to waste too much time of you. I'm new to Bitcoin and still in the learning phase. For instance, my knowledge of PSBT is quite limited. I plan to familiarize myself with these concepts and eventually contribute to RGB. It's too soon for me to join a call? Could you direct me to a developer channel (Discord, Matrix, Telegram, etc.) where I can follow along with RGB's development progress or roadmap? Also, I saw there was a dev-call; however, the most recent one was in April 2023. I believe these would be a good starting point for me.
