### ISSUE TITLE
Uable to use the rgb state command to link the wallet

### ISSUE THREAD

**Issue by Laubswind** [RGB-WG/rgb#63]
These might be newbie questions.
`
% rgb --version 
rgb-contracts 0.10.2
% rgb state 2h1ANBx-okZWRsUcx-AsyoQ9h56-oetttA7zD-k6L741i9H-GKTmcNL RGB20 -w default
Global:
  spec := (naming=(ticker=("TST"), name=("Test asset by RGB command-line"), details=~), precision=8)
  data := (terms=("SUBJECT TO, AND WITHOUT IN ANY WAY LIMITING, THE REPRESENTATIONS AND WARRANTIES OF ANY SELLER  EXPRESSLY SET FORTH IN THIS AGREEMENT OR ANY OTHER EXPRESS OBLIGATION OF SELLERS PURSUANT TO THE TERMS HEREOF, AND ACKNOWLEDGING THE PRIOR USE OF THE PROPERTY AND PURCHASER’S OPPORTUNITY  TO INSPECT THE PROPERTY, PURCHASER AGREES TO PURCHASE THE PROPERTY “AS IS”, “WHERE IS”,  WITH ALL FAULTS AND CONDITIONS THEREON. ANY WRITTEN OR ORAL INFORMATION, REPORTS, STATEMENTS,  DOCUMENTS OR RECORDS CONCERNING THE PROPERTY PROVIDED OR MADE AVAILABLE TO PURCHASER, ITS AGENTS OR CONSTITUENTS BY ANY SELLER, ANY SELLER’S AGENTS, EMPLOYEES OR THIRD PARTIES REPRESENTING OR PURPORTING TO REPRESENT ANY SELLER, SHALL NOT BE REPRESENTATIONS OR WARRANTIES, UNLESS SPECIFICALLY SET FORTH HEREIN. IN PURCHASING THE PROPERTY OR TAKING OTHER ACTION HEREUNDER, PURCHASER HAS NOT AND SHALL NOT RELY ON ANY SUCH DISCLOSURES, BUT RATHER, PURCHASER SHALL RELY ONLY ON PURCHASER’S OWN INSPECTION OF THE PROPERTY AND THE REPRESENTATIONS AND WARRANTIES  HEREIN. PURCHASER ACKNOWLEDGES THAT THE PURCHASE PRICE REFLECTS AND TAKES INTO ACCOUNT THAT THE PROPERTY IS BEING SOLD “AS IS”.
"), media=~)
  issuedSupply := (100000000000000)
  created := (1687969158)

Owned:
  assetOwner:
    amount=100000000000000, utxo=ca43e9a01782343c78fa67cc20d75d81545a8d38a031d361180c36c088639fed:0, witness=~ # owner unknown
% rgb utxos 
% 
`
When I tried the demo process in the https://www.youtube.com/watch?v=P5UQJAaan0I (RGB 0.10 realease Part IV), I failed to link the wallet to the contract (after I issued the contract and created the wallet). It suppossed to have derivation right?
BTW, for the command "rgb invoice" in the demo, how should I construct the Seal (tapret1st:xxxxx) from tx?

**Comment by dr-orlovsky** [comment]
v0.10 is made obsolete with v0.11. In v0.10 we didn't have any wallet functionality - one must program or do a lot of manual work using a bitcoin wallet aside. That is changed with v0.11, which will be released before the NW.
