### ISSUE TITLE
rgb-wallet compile failed

### ISSUE THREAD

**Issue by Wsscrypto** [RGB-WG/rgb#91]
error: ailed to run custom build command for `openssl-sys v0.9.98`
error: he system library `openssl` required by crate `openssl-sys` was not found.

Im used docker ubuntu:latest image, and run on container。
But compile failed because of library，and fix it by install follow thing：

$ apt install libssl-dev

Maybe $ apt install pkg-config   is not enough

**Comment by cymqqqq** [comment]
yes, try sudo apt install libssl-dev
and 
 sudo apt install pkg-config
 sudo apt-get install libudev-dev
