### ISSUE TITLE
add support for electrum server

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#95]
Currently, the only supported explorer is `esplora`. It would be useful to also be able to use an electrum server (e.g. `electrs`) as was the case in RGB v0.10.

`electrs` requires less resources than `esplora` and current RGB developers and users already rely on an electrum server, so switching to `esplora` requires quite some work and is therefore not ideal.

I know esplora was the fastest solution but I think having electrum server support is still worth it. @dr-orlovsky can you please add electrum server support?

**Comment by dr-orlovsky** [comment]
This would require rewriting rust-electrum crate to use BP instead of rust-bitcoin, which is a non-trivial and would require about a week of work just on this task. esplora crate was much smaller and that was another reason to use it for v0.11

**Comment by zoedberg** [comment]
I'm not sure a rewrite of the rust-electrum crate is necessary, I think we can use raw methods and convert the server responses to BP structures directly in the implementation of the Resolver.

Is it ok for you @dr-orlovsky if I try to implement this myself and propose a PR roughly by the end of the next week?

**Comment by dr-orlovsky** [comment]
@zoedberg the approach is fine. BTW we do not need to put any changes into anything other than `cli` - the Runtime should work with any resolver

**Comment by nicbus** [comment]
Closing as this is now done.
