### ISSUE TITLE
suppress "stock file is absent, creating a new one" eprint

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#99]
Instantiating a runtime by calling `Runtime::load_attach()` currently prints `stock file is absent, creating a new one`.

This is inconvenient and I think this output should be suppressed.
Similarly to what's been done in #23, I propose to protect that `eprint` behind a feature flag (e.g. `log`, which appears otherwise unused).

**Comment by dr-orlovsky** [comment]
Agree
